# This is a basic workflow to help you get started with Actions

name: docker CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  opam:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coq_version:
          - '8.13'
        ocaml_version:
          - 'minimal'
    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: './coq-hierarchy-builder.opam'
        coq_version: ${{ matrix.coq_version }}
        ocaml_version: ${{ matrix.ocaml_version }}

  hb-plan-B:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: './coq-hierarchy-builder.opam'
        coq_version: '8.13'
        ocaml_version: 'minimal'
        script: |
          mkdir /home/coq/workspace
          cp -ra . /home/coq/workspace
          cd /home/coq/workspace
          opam install ./coq-hierarchy-builder.opam
          sed -i "s/-Q . HB//" _CoqProject.test-suite
          # This is what a user does to cut HB loose
          COQ_ELPI_ATTRIBUTES=log_hb make test-suite -j2
          hb patch `find . -name \*.v`
          make clean
          opam remove coq-hierarchy-builder
          opam install ./coq-hierarchy-builder-shim.opam
          # Does it work?
          make test-suite -j2
          # We also test the reset facility works (we rebuild hb locally)
          make hb
          ./hb reset `find . -name \*.v`
          git diff --exit-code
